function = plot(x,y1,y2,y3)
plot(x,y1,'-s','MarkerSize',5,...
    'MarkerEdgeColor','blue',...
    'MarkerFaceColor',[0 0 1])
hold on
plot(x,y2,'-s','MarkerSize',5,...
    'MarkerEdgeColor','red',...
    'MarkerFaceColor',[1 0 0])
hold on
plot(x,y3,'-s','MarkerSize',5,...
    'MarkerEdgeColor','y',...
    'MarkerFaceColor',[0 .3 .5 ]),ylabel('Classifier accuracy'),xlabel('Percent Selected feature'),legend('ACO','GA','ACO-GA');
hold off;
end